name: webfeed
version: 0.1.0
description: A dart package for parsing web feed.
author: Wito Chandra <wito.c.91@gmail.com>
dependencies:
  xml: "^3.0.0"
dev_dependencies:
  test: ^0.12.0
  http: "^0.11.3+16"